services:
  mosquitto:
    image: eclipse-mosquitto
    hostname: mosquitto
    restart: unless-stopped
    ports:
      - "1883:1883"
      - "9001:9001"
    volumes:
      - mosquitto_data:/mosquitto/data
      - ./mosquitto/config:/mosquitto/config:rw
      - ./mosquitto/log:/mosquitto/log:rw
    networks:
      - biosafe_network

  node_red:
    image: nodered/node-red
    hostname: node_red
    restart: unless-stopped
    ports:
      - "1880:1880"
    volumes:
      - ./nodered_data:/data:rw
    networks:
      - biosafe_network

  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: digitalStorage
      MYSQL_USER: user
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - biosafe_network

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    restart: unless-stopped
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "8081:80"
    networks:
      - biosafe_network
    depends_on:
      - mysql

  mqttx:
    image: emqx/mqttx-web
    hostname: mqttx
    restart: unless-stopped
    ports:
      - "80:80"
    networks:
      - biosafe_network

networks:
  biosafe_network:
    driver: bridge

volumes:
  config:
  data:
  log:
  mysql_data:
  mosquitto_data:
